### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by Actoba** [Actoba/roll20-character-sheets#20]
Pre -release checklist
- [x] Populate help tab
- [x] verify json file
- [x] Update readme
- [x] Merge/rebase from master
- [x] Merge 5e branch back into master
- [ ] submit pull request to upstream/master
